# Training Configuration
training:
  num_epochs: 1
  steps_per_epoch: 20
  save_every: 5
  eval_every: 5

# Model Configuration
model:
  name: "Qwen/Qwen3-0.6B"
  max_tokens: 100

# GRPO Configuration
grpo:
  learning_rate: 1e-5
  rollouts_per_step: 8

# Data Configuration
data:
  train_path: "data/train_data_structured.json"
  test_path: "data/test_data_structured.json"

# Output Configuration
output:
  checkpoint_dir: "training/checkpoints/web-browsing-qwen3"
  output_dir: "training/outputs/web-browsing-qwen3" 
